---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      # - JELLYFIN_PublishedServerUrl=192.168.15.16 #optional
    volumes:
      - /home/liber/config/jellyfin:/config
      - /home/liber/media/tv:/data/tvshows
      - /home/liber/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      # - USER=username #optional
      # - PASS=password #optional
      # - WHITELIST=iplist #optional
      # - PEERPORT=peerport #optional
      # - HOST_WHITELIST=dnsname list #optional
    volumes:
      - /home/liber/config/transmission:/config
      - /home/liber/media/downloads:/downloads
      - /home/liber/media/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/liber/config/sonarr:/config
      - /home/liber/media/tv:/tv #optional
      - /home/liber/media/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/liber/config/radarr:/config
      - /home/liber/media/movies:/movies #optional
      - /home/liber/media/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/liber/config/bazarr:/config
      - /home/liber/media/movies:/movies #optional
      - /home/liber/media/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped